services:
  meilisearch:
    image: getmeili/meilisearch:v1.10
    ports:
      - "7700:7700"
    environment:
      MEILI_ENV: development
      MEILI_MASTER_KEY: masterKey
    volumes:
      - meili_data:/meili_data

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: meili_demo
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  meili_data:
  db_data: